import { createClient } from '@supabase/supabase-js'
import { NextResponse } from 'next/server'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

const RESEND_API_KEY = process.env.RESEND_API_KEY || ''
const ADMIN_EMAIL = 'mayurshreeja@gmail.com'

async function sendEmail(to: string[], subject: string, html: string) {
  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${RESEND_API_KEY}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      from: 'onboarding@resend.dev',
      to: [ADMIN_EMAIL], // Resend free plan - only to verified email
      subject,
      html
    })
  })
  return res.json()
}

function emailTemplate(title: string, body: string, color: string = '#1F3864') {
  return `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
      <div style="background:${color};color:#fff;padding:20px;border-radius:8px 8px 0 0">
        <h2 style="margin:0">🏭 Mayur Operations System</h2>
        <p style="margin:4px 0 0;opacity:0.8;font-size:14px">Mayur Food Packaging Products — Bawana, Delhi</p>
      </div>
      <div style="background:#fff;padding:20px;border:1px solid #E0E0E0;border-top:none">
        <h3 style="color:${color};margin-top:0">${title}</h3>
        ${body}
      </div>
      <div style="background:#F5F5F5;padding:12px 20px;border-radius:0 0 8px 8px;font-size:12px;color:#666;border:1px solid #E0E0E0;border-top:none">
        <a href="https://mayur-mos.vercel.app" style="color:#1F3864;font-weight:bold">mayur-mos.vercel.app</a> | Auto-generated by MOS System
      </div>
    </div>
  `
}

export async function POST(req: Request) {
  const body = await req.json()
  const { type } = body
  const today = new Date().toISOString().split('T')[0]

  if (type === 'daily_report') {
    const { data: prod } = await supabase.from('production').select('plant,good_parts,rejection,shift').eq('date', today)
    const { data: bd } = await supabase.from('breakdowns').select('status,downtime_min').eq('date', today)
    const { data: mc } = await supabase.from('mould_changes').select('on_time').eq('date', today)
    const { data: pm } = await supabase.from('mould_master').select('status').eq('status', 'OVERDUE')

    const totalGood = prod?.reduce((a,r)=>a+(r.good_parts||0),0)||0
    const totalRej = prod?.reduce((a,r)=>a+(r.rejection||0),0)||0
    const rejPct = (totalGood+totalRej)>0?Math.round(totalRej/(totalGood+totalRej)*100*10)/10:0
    const bdPending = bd?.filter(r=>r.status==='Pending').length||0
    const totalDown = bd?.reduce((a,r)=>a+(r.downtime_min||0),0)||0
    const mcTotal = mc?.length||0
    const mcOnTime = mc?.filter(r=>r.on_time==='Yes').length||0
    const pmOverdue = pm?.length||0

    const htmlBody = `
      <table style="width:100%;border-collapse:collapse">
        <tr style="background:#F5F5F5"><td style="padding:10px;font-weight:bold;border:1px solid #E0E0E0">📅 Date</td><td style="padding:10px;border:1px solid #E0E0E0">${today}</td></tr>
        <tr><td style="padding:10px;font-weight:bold;border:1px solid #E0E0E0">✅ Good Parts</td><td style="padding:10px;border:1px solid #E0E0E0;color:#276221;font-weight:bold">${totalGood.toLocaleString()} pcs</td></tr>
        <tr style="background:#F5F5F5"><td style="padding:10px;font-weight:bold;border:1px solid #E0E0E0">❌ Rejection</td><td style="padding:10px;border:1px solid #E0E0E0;color:${rejPct>3?'#C00000':'#276221'};font-weight:bold">${rejPct}% (${totalRej.toLocaleString()} pcs)</td></tr>
        <tr><td style="padding:10px;font-weight:bold;border:1px solid #E0E0E0">🔧 Breakdown</td><td style="padding:10px;border:1px solid #E0E0E0;color:${bdPending>0?'#C00000':'#276221'}">${bdPending} pending | ${totalDown} min downtime</td></tr>
        <tr style="background:#F5F5F5"><td style="padding:10px;font-weight:bold;border:1px solid #E0E0E0">🔄 Mould Change</td><td style="padding:10px;border:1px solid #E0E0E0">${mcOnTime}/${mcTotal} on time</td></tr>
        <tr><td style="padding:10px;font-weight:bold;border:1px solid #E0E0E0">⚙️ PM Overdue</td><td style="padding:10px;border:1px solid #E0E0E0;color:${pmOverdue>0?'#C00000':'#276221'};font-weight:bold">${pmOverdue} moulds</td></tr>
      </table>
      <br><a href="https://mayur-mos.vercel.app" style="background:#1F3864;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:bold">MOS Dashboard Kholo →</a>
    `

    const result = await sendEmail([ADMIN_EMAIL], `MOS Daily Report — ${today}`, emailTemplate('📊 Daily Production Report', htmlBody))
    if (result.id) {
      return NextResponse.json({ success: true, msg: `Daily report sent to ${ADMIN_EMAIL}!` })
    } else {
      return NextResponse.json({ success: false, msg: `Error: ${JSON.stringify(result)}` })
    }
  }

  if (type === 'pm_overdue_alert') {
    const { data: overdueMoulds } = await supabase.from('mould_master').select('mould_name,plant,current_shots,next_pm_at_shots').eq('status','OVERDUE')
    if (!overdueMoulds?.length) return NextResponse.json({ success: true, msg: 'Koi PM overdue nahi!' })
    const rows = overdueMoulds.map(m=>`<tr><td style="padding:8px;border:1px solid #E0E0E0">${m.mould_name}</td><td style="padding:8px;border:1px solid #E0E0E0">${m.plant}</td><td style="padding:8px;border:1px solid #E0E0E0;color:#C00000">${(m.current_shots||0).toLocaleString()} shots</td></tr>`).join('')
    const htmlBody = `<p style="color:#C00000;font-weight:bold">${overdueMoulds.length} moulds PM overdue!</p><table style="width:100%;border-collapse:collapse"><thead><tr style="background:#1F3864;color:#fff"><th style="padding:8px;text-align:left">Mould</th><th style="padding:8px;text-align:left">Plant</th><th style="padding:8px;text-align:left">Shots</th></tr></thead><tbody>${rows}</tbody></table>`
    const result = await sendEmail([ADMIN_EMAIL], `⚙️ PM Overdue — ${overdueMoulds.length} Moulds`, emailTemplate('Mould PM Overdue!', htmlBody, '#854F0B'))
    return NextResponse.json({ success: result.id?true:false, msg: result.id?'PM alert sent!':JSON.stringify(result) })
  }

  if (type === 'breakdown_alert') {
    const { plant, machine, problem, operator } = body
    const htmlBody = `
      <table style="width:100%;border-collapse:collapse">
        <tr><td style="padding:8px;font-weight:bold;border:1px solid #E0E0E0">Plant</td><td style="padding:8px;border:1px solid #E0E0E0">${plant}</td></tr>
        <tr style="background:#F5F5F5"><td style="padding:8px;font-weight:bold;border:1px solid #E0E0E0">Machine</td><td style="padding:8px;border:1px solid #E0E0E0">${machine}</td></tr>
        <tr><td style="padding:8px;font-weight:bold;border:1px solid #E0E0E0">Problem</td><td style="padding:8px;border:1px solid #E0E0E0">${problem}</td></tr>
        <tr style="background:#F5F5F5"><td style="padding:8px;font-weight:bold;border:1px solid #E0E0E0">Operator</td><td style="padding:8px;border:1px solid #E0E0E0">${operator}</td></tr>
        <tr><td style="padding:8px;font-weight:bold;border:1px solid #E0E0E0">Time</td><td style="padding:8px;border:1px solid #E0E0E0">${new Date().toLocaleTimeString('en-IN')}</td></tr>
      </table>
    `
    const result = await sendEmail([ADMIN_EMAIL], `🚨 Breakdown — ${plant} ${machine}`, emailTemplate('Breakdown Alert!', htmlBody, '#C00000'))
    return NextResponse.json({ success: result.id?true:false, msg: result.id?'Breakdown alert sent!':JSON.stringify(result) })
  }

  if (type === 'stock_alert') {
    const { data: criticalItems } = await supabase.from('ims_stock').select('item_name,stock_cartons').eq('date', today).lte('stock_cartons', 10)
    if (!criticalItems?.length) return NextResponse.json({ success: true, msg: 'Koi critical stock nahi!' })
    const rows = criticalItems.map(i=>`<tr><td style="padding:8px;border:1px solid #E0E0E0">${i.item_name}</td><td style="padding:8px;border:1px solid #E0E0E0;color:#C00000">${i.stock_cartons} Ctn</td></tr>`).join('')
    const htmlBody = `<p style="color:#C00000;font-weight:bold">${criticalItems.length} items critical!</p><table style="width:100%;border-collapse:collapse"><thead><tr style="background:#C00000;color:#fff"><th style="padding:8px;text-align:left">Item</th><th style="padding:8px;text-align:left">Stock</th></tr></thead><tbody>${rows}</tbody></table>`
    const result = await sendEmail([ADMIN_EMAIL], `📦 Stock Alert — ${criticalItems.length} Items`, emailTemplate('Stock Critical!', htmlBody, '#C00000'))
    return NextResponse.json({ success: result.id?true:false, msg: result.id?'Stock alert sent!':JSON.stringify(result) })
  }

  return NextResponse.json({ success: false, msg: 'Unknown type' })
}
